version: "3"

services:
  rabbitmq:
    container_name: daas-rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
    restart: always
  mongo:
    container_name: daas-mongo
    image: mongo
    ports:
      - 27017:27017
    restart: always
  minio:
    container_name: daas-minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --address ":9000" --console-address ":9001"
    restart: always
